---
name: Cloudflare Argo Tunnel
version: 2.0
slug: cloudflare-argo
url: https://github.com/paocloud/hass-cloudflare-argo
description: Connect to Cloudflare Argo tunnel to Home Assistant instance.
codenotary: hello@paocloud.co.th
arch: 
  - armv7
  - amd64
  - aarch64
  - armhf
  - i386
startup: application
hassio_api: true
boot: auto
host_network: false
apparmor: true
map: 
  - config:ro
options:
  hostname: ""
  uuid: ""
schema:
  hostname: str
  uuid: str
