---
name: Cloudflare Argo Tunnel - Host
version: 2.1
slug: cloudflare-argo-host
url: https://github.com/paocloud/hass-cloudflare-argo
description: Connect to Cloudflare Argo tunnel to Home Assistant instance.
codenotary: hello@paocloud.co.th
arch: 
  - armv7
  - amd64
  - aarch64
  - armhf
  - i386
startup: application
hassio_api: true
boot: auto
host_network: true
apparmor: true
map: 
  - config:ro
